### ISSUE TITLE
#51 still same bug (with png images)

### ISSUE THREAD

**Issue by smolleyes** [open-xml-templating/docxtemplater-image-module#54]
hello

i still have this strange bug 

same code with 188 (png) thumbnails for a size of 43 MO total, it fail on the doc.render();

no idears? 

thanks

**Comment by smolleyes** [comment]
watching at this function 

decodeImage(oldFile, imgName, num, imgNum) {
		var mockedQrCode = {xmlTemplater: this.xmlTemplater, imgName: imgName, data: oldFile.asBinary(), num: num};
		if (!/\.png$/.test(oldFile.name)) {
			return this.imageSetter(mockedQrCode);
		}
		return ((imgName) => {
			var base64 = base64encode(oldFile.asBinary());
			var binaryData = new Buffer(base64, "base64");
			var png = new PNG(binaryData);
			var finished = (a) => {
				png.decoded = a;
				try {
					this.qr[imgNum] = new DocxQrCode(png, this.xmlTemplater, imgName, num, this.getDataFromString);
					return this.qr[imgNum].decode(this.imageSetter);
				}
				catch (e) {
					return this.imageSetter(mockedQrCode);
				}
			};
			return png.decode(finished);
		})(imgName);
	}

i converted all my thumbnaisl to jpg and now it works, problem with png images encoding (but it s already png files i don t understand why it s reencoded)

**Comment by edi9999** [comment]
Strange, this code shouldn't run on version 1.0 if you haven't set qrCode:true in the options.

Can you update versions and see if it solves it ?

**Comment by edi9999** [comment]
I've tested it and it really seems that if you don't set qrCode to true, the code shouldn't be running on the latest version. If it still happens, can you please post a minimal example to reproduce ?

**Comment by edi9999** [comment]
I'm able to reproduce this with 50 images of a size of 500kb each.

**Comment by smolleyes** [comment]
hello

'cool' for me it s ok but only with jpg/jpeg images if i use png i have the problem :/

**Comment by DankoHR** [comment]
I'm using JPG images exclusively and the problem occures anyway.
I have the feeling that it is also related to the overall filesize of the images, but i haven't verified that yet.

**Comment by smolleyes** [comment]
humm strange since now i can load a lot of images let me know if you 
need some tests :)

**Comment by edi9999** [comment]
I've pushed a fix to docxtemplater which fixes an other memory allocation error, maybe it might solve this issue too, but I think both issues are quite unrelated. See https://github.com/open-xml-templating/docxtemplater/issues/223

**Comment by DankoHR** [comment]
I've just tried it with the new version V2.1.1 of docxtemplater. Unfortunately it does not solve this issue.

**Comment by DankoHR** [comment]
FYI 
I've debugged the image module today and found out that probably the zipper module JSZip causes the issue. In case you remove/comment the line "this.zip.file(file.name, file.data, file.options);" under the function "addImageRels" (found in imgManager.js) the issue disappears. Of course then no images will be shown in the word document, as they are missing.

I've solved my issue by replacing the zip functionality with 7zip (executing binary with command line arguments). The performance now is also way better. Unfortunately I've modified your code at many places to fit my requirements, so i can't share my solution here easily.

**Comment by edi9999** [comment]
I  have tried to reproduce with code that only tests JSZip outside of the context of docxtemplater but haven't encountered the memory leak with thousand files of 50kb each, so I guess the issue is somewhere at the interface between docxtemplater and jszip, but I don't know where

**Comment by smolleyes** [comment]
hi

can t you share you fix DankoHr ?

thanks

**Comment by smolleyes** [comment]
hello @edi9999 

think it might be a good fix to replace jsZIP by 7zip or something else like DankoHR did :)

PR dankoHR !! :p 

thanks

**Comment by edi9999** [comment]
I dont think it is a good idea to use 7zip in the general library. First it is in the command line, which makes it impossible to work in the commandline. Second, it is probably just a small bug in docxtemplater or jszip, but the problem is rather that the issue is not that easy to investigate.

**Comment by smolleyes** [comment]
hello

i agree...

i resized my images and removed white background and now it works (had a 
very big doc to generate) :p

thanks
